# Generated by Django 4.0.4 on 2022-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('classe', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('shortname', models.CharField(max_length=30)),
                ('keyname', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('image_thumb', models.URLField()),
                ('limit', models.IntegerField()),
                ('stack', models.IntegerField()),
                ('obs_1', models.TextField()),
                ('obs_2', models.TextField()),
            ],
        ),
    ]
