# Generated by Django 4.0.4 on 2022-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_image_alter_item_image_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_thumb',
            field=models.CharField(default='', max_length=120),
        ),
    ]
